
import pandas as pd
from datetime import datetime
import json




body = {
   "task":{
      "id":"eb10fb67-bb4a-4174-bdf5-fc68da5d26ba",
      "status":"successful",
      "createdAt":1719282775546,
      "finishedAt":1719282839358,
      "retriedOriginalTaskId":"ac07672d-aad5-4048-a9c4-a10357685281",
      "retriedTaskId":"ac07672d-aad5-4048-a9c4-a10357685281",
      "retriedByTaskId":None,
      "startedAt":1719282776782,
      "robotId":"8560b547-1aae-4318-ae81-f679b8e5abbe",
      "triedRecordingVideo":False,
      "robotBulkRunId":None,
      "runByAPI":False,
      "runByTaskMonitorId":"fac8526c-9b99-4efa-aefb-340c396caa78",
      "runByUserId":None,
      "userFriendlyError":None,
      "inputParameters":{
         "originUrl":"https://www.wimoveis.com.br/imoveis-venda-distrito-federal-publicado-no-ultimo-dia-ordem-publicado-maior.html",
         "extracao_wimoveis_limit":300
      },
      "videoRemovedAt":None,
      "videoUrl":None,
      "capturedDataTemporaryUrl":None,
      "capturedTexts":{
         
      },
      "capturedScreenshots":{
         
      },
      "capturedLists":{
         "extracao wimoveis":[
            {
               "_STATUS":"REMOVED",
               "Position":None,
               "_PREV_Position":"1",
               "Valor":None,
               "_PREV_Valor":"R$ 2.271.206",
               "Condominio":None,
               "_PREV_Condominio":None,
               "Titulo":None,
               "_PREV_Titulo":"SQNW 305 BLOCO H - YARD NOROESTE",
               "Local":None,
               "_PREV_Local":"Noroeste, Brasília",
               "Area":None,
               "_PREV_Area":"135 m² tot.",
               "Quartos":None,
               "_PREV_Quartos":"3 quartos",
               "Banheiro":None,
               "_PREV_Banheiro":"3 ban.",
               "Garagens":None,
               "_PREV_Garagens":"2 vaga",
               "Descricao":None,
               "_PREV_Descricao":"Sofisticação e modernidade que fazem a vida fluir com naturalidade. O Yard Noroeste está localizado na sqnw 305 Bloco H e é o lugar feito para se desenvolverem os melhores sentimentos. Sua família terá espaço e opções de lazer para todos aproveitarem cada minutinho em casa. Com um verdadeiro quintal vertical à sua disposição para aliviar a rotina, assim fica fácil deixar a vida florescer de um jeito mais leve e tranquilo. Apartamento de 03 quartos e 2 vagas de garagem. - 1 suíte + 2 semissuítes. - Sala de estar. - Sala de jantar. - Lavabo. - Varanda Gourmet. - Cozinha com área e banheiro de serviço. - Despensa. - Fechadura biométrica na porta da entrada social. - Piso em porcelanato 90x90cm. - Janelas de correr. - Luminárias de led. Pilotis: - Brinquedoteca. - Espaço Gourmet. - Salão de Festas. Cobertura Social: - Piscina com Deck; - Espaço Gourmet. - Terraço Gourmet. - Sauna. - Academia. - Espaço Funcional. - Churrasqueira. Saiba tudo sobre esse empreendimento de alto padrão do Noroeste. Ligue agora, fale com um especialista quadraimob. Quadraimob soluções imobiliárias. (61) Ver dados. (61) Ver dados – WhatsAppSofisticação e modernidade que fazem a vida fluir com naturalidade. O Yard Noroeste está localizado na sqnw 305 Bloco B e é o lugar feito para se desenvolverem os melhores sentimentos. Sua família terá espaço e opções de lazer para todos aproveitarem cada minutinho em casa. Com um verdadeiro quintal vertical à sua disposição para aliviar a rotina, assim fica fácil deixar a vida florescer de um jeito mais leve e tranquilo. Pilotis: - Brinquedoteca. - Espaço Gourmet. - Salão de Festas. Cobertura Social: - Piscina com Deck; - Espaço Gourmet. - Terraço Gourmet. - Sauna. - Academia. - Espaço Funcional. - Churrasqueira. Apartamento de 03 quartos e 2 vagas de garagem. - 1 suíte + 2 semissuítes. - Sala de estar. - Sala de jantar. - Lavabo. - Varanda Gourmet. - Cozinha com área e banheiro de serviço. - Despensa. - Fechadura biométrica na porta da entrada social. - Piso em porcelanato 90x90cm. - Janelas de correr. - Luminárias de led nos acessórios do banheiro. Saiba tudo sobre esse empreendimento de alto padrão do Noroeste. Ligue agora, fale com um especialista quadraimob. Quadraimob soluções imobiliárias. (61) Ver dados",
               "Link":None,
               "_PREV_Link":"https://www.wimoveis.com.br/propriedades/3-quartos-2-vagas-de-garagem-yard-noroeste-2985035024.html"
            },
            {
               "_STATUS":"ADDED",
               "Position":"1",
               "Valor":"R$ 330.000",
               "Condominio":"R$ 587 Condominio",
               "Titulo":"QMSW 4 LOTE 9 2° ANDAR",
               "Local":"Sudoeste, Brasília",
               "Area":"27 m² tot.",
               "Quartos":"1 quartos",
               "Banheiro":"1 banheiro",
               "Garagens":"1 vaga",
               "Descricao":"Daleprane inteligência imobiliária vende kit. excelente oportunidade. corretor responsável: daleprane inteligência imobiliária Creci: Ver dados. carlos santos – creci 26908. (61) 9 Ver dados. sobre O imóvel: obs: Fotos corresponde a outa unidade. - 27m²; - Nascente; - Vista livre; - Sala; - Quarto privativo; - Cozinha; - Banheiro grande; - Vaga coberta; sobre O condomínio: - Portaria 24 horas; - Elevador. Proximidades: agende já A sua visita! A daleprane oferece: - Avaliação mercadológica gratuita de imóveis para venda e locação; - Fotos, vídeos e tour 360º, profissionais; - Venda rápida e segura; - Anúncios patrocinados nos principais sites imobiliários de Brasília; - Assessoria jurídica e proteção ao seu patrimônio; - Correspondente bancário, acompanhando o financiamento habitacional do início ao fim; - Reformas e projetos de interiores; Venha para a Daleprane e tenha uma experiência extraordinária! #SeuImóvelSemStress",
               "Link":"https://www.wimoveis.com.br/propriedades/r4-330.000-kit-27m2-2988290335.html"
            },
            {
               "_STATUS":"REMOVED",
               "Position":None,
               "_PREV_Position":"2",
               "Valor":None,
               "_PREV_Valor":"R$ 549.000",
               "Condominio":None,
               "_PREV_Condominio":None,
               "Titulo":None,
               "_PREV_Titulo":"Qd Qe 19,",
               "Local":None,
               "_PREV_Local":"Guará II, Brasília",
               "Area":None,
               "_PREV_Area":"132 m² tot.",
               "Quartos":None,
               "_PREV_Quartos":"2 quartos",
               "Banheiro":None,
               "_PREV_Banheiro":"2 ban.",
               "Garagens":None,
               "_PREV_Garagens":"3 vaga",
               "Descricao":None,
               "_PREV_Descricao":"Guará ii, qe 19, excelente casa térrea com 132, 30 m² de área construída, em terreno de 120 m². Imóvel exclusivo. Composta por 2 quartos, sendo 1 suíte, ar condicionado, Sala ampla, cozinha com armários, área de serviço, , banheiro social, garagem para 3 carros. Casa ampla, confortável, arejada, com excelente localização ao final da rua, em uma das melhores quadras do Guará. Perto de vias de acesso, supermercados e escolas. Aceita Financiamento e fgts. Agende sua visita! Bruno Farias. Ver dados. tau Imóveis. A área do imóvel anunciado é uma estimativa e deverá ser confirmada junto a certidão de ônus do imóvel ou cessão de direitos. Faça a avaliação do seu imóvel com nossa equipe e se surpreenda com os resultados. Tau Imóveis, ajuda você a realizar o seu sonho. São mais de 10 anos de experiência em vendas de imóveis, sempre com total segurança e tranquilidade para os nossos clientes.",
               "Link":None,
               "_PREV_Link":"https://www.wimoveis.com.br/propriedades/casa-terrea-2-quartos-suite-qe-19-guara-ii-2996667204.html"
            },
            {
               "_STATUS":"ADDED",
               "Position":"2",
               "Valor":"R$ 720.000",
               "Condominio":"R$ 488 Condominio",
               "Titulo":"Rua 18",
               "Local":"Aguas Norte, Águas Claras",
               "Area":"67 m² tot.",
               "Quartos":"2 quartos",
               "Banheiro":"1 vaga",
               "Garagens":None,
               "Descricao":"Wave Residence belíssimo apartamento: Recém reformado. 2 suítes. Projeto de iluminação. Piso em porcelanato polido. Revestimento dos banheiros em porcelanato. Armários novos. Ampla Varanda. Vista livre. Nascente. Condomínio com lazer completo: Piscina. Academia completa. Brinquedoteca. Sala de jogos. Sala de estudos. Hidromassagem. Sauna. Salão de festas. Valor do condomínio: água e gás incluso por apenas R$ 488. 00 /mês. Prédio em frente ao parque de águas claras. cj 28. 770 ->. Serra Negra Imobiliária e empreendimentos. Avaliamos e vendemos seu imóvel em todo o df! Estuda proposta. Todos os valores anunciados podem ser alterados sem prévio aviso. Acesse nossa rede social: @serranegraimobiliariadf - 14/03/2024",
               "Link":"https://www.wimoveis.com.br/propriedades/wave-residence-recem-reformado-2-quartos-nascente-2994286505.html"
            },
            {
               "_STATUS":"REMOVED",
               "Position":None,
               "_PREV_Position":"3",
               "Valor":None,
               "_PREV_Valor":"R$ 620.000",
               "Condominio":None,
               "_PREV_Condominio":None,
               "Titulo":None,
               "_PREV_Titulo":"Quadra QE 28 0",
               "Local":None,
               "_PREV_Local":"Guara II, Guará",
               "Area":None,
               "_PREV_Area":"200 m² tot.",
               "Quartos":None,
               "_PREV_Quartos":"4 quartos",
               "Banheiro":None,
               "_PREV_Banheiro":"2 ban.",
               "Garagens":None,
               "_PREV_Garagens":"3 vaga",
               "Descricao":None,
               "_PREV_Descricao":"Oportunidade! Casa à venda na qe 28 - Guará ii. Casa para reforma em lote de 200m² com casa de fundos, Ideal para investimento e em localização privilegiada. Entre em contato e agenda sua visita. Casa principal: - Sala ampla. - 3 quartos sendo 1 com armários. - Banheiro social com box. -Cozinha com armários. - Área de serviço. - 3 vagas de garagem cobertas. Casa dos fundos: -Forro Pvc. -Sala com cozinha americana e armários planejados. -Suíte com box. -Área de serviço e corredor de acesso. aceita financiamento E fgts. A área do imóvel anunciado é uma estimativa e deverá ser confirmada junto à certidão de ônus do imóvel ou na Secretaria da Fazenda do df. Valores e condições sujeitos a alteração sem prévio aviso. - 22/06/2024",
               "Link":None,
               "_PREV_Link":"https://www.wimoveis.com.br/propriedades/qe-28-200m-04-quartos-guara-ii-df-2994630427.html"
            },
            {
               "_STATUS":"ADDED",
               "Position":"3",
               "Valor":"R$ 360.000",
               "Condominio":None,
               "Titulo":"CNB 06 Taguatinga Norte",
               "Local":"Taguatinga Norte, Taguatinga",
               "Area":"72 m² tot.",
               "Quartos":"2 quartos",
               "Banheiro":"2 ban.",
               "Garagens":None,
               "Descricao":"Excelente oportunidade de adquirir um apartamento com 2 dormitórios, sendo 1 suíte, e 1 banheiro, com uma área privativa de 72m². Este imóvel possui uma posição solar privilegiada, com o Sol da manhã e da tarde iluminando todos os cômodos. Possui uma suíte, 1 banheiro social, sala ampla, cozinha e uma boa área de serviço. O piso do apartamento foi trocado recentemente. Está com armários Planejados e pronto para morar. Localizado no bairro Taguatinga Norte, este apartamento está em um condomínio com portaria 24 horas, proporcionando segurança e conforto aos moradores. O prédio conta dois elevadores novos, salão de festas e portaria com identificação biométrica e porteiro. Além disso, a região oferece uma ampla gama de serviços e comércios, como academia, farmácia, padaria, shopping, supermercado e transporte público, garantindo praticidade e comodidade no dia a dia. Se você está em busca de um novo lar, esta é a oportunidade perfeita para você. Agende uma visita e conheça mais detalhes deste incrível apartamento à venda no bairro Taguatinga Norte. Invista em qualidade de vida e segurança para você e sua família. Comprar um apartamento neste local privilegiado é a escolha certa para quem busca conforto e praticidade no seu dia a dia. Formas de pagamento: À vista, aceita financiamento bancário e fgts. Aprovação de crédito junto a diversas instituições financeiras com as melhores taxas e rapidez. Venha conhecer esse lindo apartamento! Ligue e marque sua visita. A área do imóvel anunciado é uma estimativa e deve ser confirmada pelo pretendente interessado junto à Certidão de Ônus do Imóvel. Valores e condições sujeitos à alteração sem prévio aviso. Agende sua visita! 61 – Ver dados (whatsapp)",
               "Link":"https://www.wimoveis.com.br/propriedades/2-quartos-cnb-06-taguatinga-norte-garagem-suite-2997478881.html"
            },
            {
               "_STATUS":"CHANGED",
               "Position":"4",
               "_PREV_Position":"8",
               "Valor":"Consultar preço",
               "Condominio":"Consultar preço",
               "Titulo":"Rua Quaresmeira 2ª, Lote 13",
               "Local":"Guara I, Guará",
               "Area":"1 plan.",
               "Quartos":"3 quartos",
               "Banheiro":None,
               "Garagens":None,
               "Descricao":"Seja bem-vindo(a) ao Ilha Bela Residence, apartamento de 3 quartos, sendo 1 suíte e 2 semissuítes e 02 vagas de garagem, no Guará I: Experimente o Excepcional. Mais um empreendimento com a marca da solidez, segurança e qualidade construtiva Emplavi, há 41 anos construindo histórias felizes em Brasília, com mais 31. 000 imóveis entregues no prazo. A simetria perfeita entre beleza arquitetônica e funcionalidade, no lugar ideal para os melhores momentos em família ou na companhia dos amigos, com lazer completo e diferenciado, áreas comuns diversificadas e funcionais e espaços amplos revestidos de requinte e sofisticação, que proporcionam conforto e praticidade, o Ilha Bela residence apresenta uma proposta única de viver e morar em Brasília, com a qualidade de vida que você e sua família sempre sonharam, harmonizando a intensidade da uma grande cidade, com momentos únicos de convivência, relaxamento e muita diversão. O Ilha Bela Residence está localizado no Guará I, em frente à eptg, a poucos minutos do Plano Piloto e com acesso rápido a toda uma gama de equipamentos públicos, parques, shoppings, supermercados, feiras, escolas, farmácias e comércio em geral e às principais vias de acesso ao centro de Brasília, além de duas estações de metrô e dois terminais de ônibus. Com metragens que variam entre 97, 44m² e 109, 12m² e com 2 vagas de garagem, os apartamentos do Ilha Bela residence, oferecem uma experiência inigualável de conforto, praticidade e sofisticação, mesclando elementos nobres e contemporâneos, com um projeto definitivo, inteligente e funcional, feito para momentos únicos de convivência, aconchego e bem-viver em família. Um novo estilo de viver o excepcional espera por e você e sua família. Fale com um corretor credenciado Emplavi, agende uma visita no ponto de vendas e conheça as obras aceleradas. As imagens apresentadas são meramente ilustrativas. Unidades sujeitas à disponibilidade.",
               "Link":"https://www.wimoveis.com.br/propriedades/apartamento-03-quartos-ilha-bela-residence-guara-i-2986017670.html"
            },
            {
               "_STATUS":"REMOVED",
               "Position":None,
               "_PREV_Position":"5",
               "Valor":None,
               "_PREV_Valor":"R$ 2.700.000",
               "Condominio":None,
               "_PREV_Condominio":"R$ 200 Condominio",
               "Titulo":None,
               "_PREV_Titulo":"Rua 8 7898",
               "Local":None,
               "_PREV_Local":"Vicente Pires, Vicente Pires",
               "Area":None,
               "_PREV_Area":"800 m² tot.",
               "Quartos":None,
               "_PREV_Quartos":"4 quartos",
               "Banheiro":None,
               "_PREV_Banheiro":"6 ban.",
               "Garagens":None,
               "_PREV_Garagens":"4 vaga",
               "Descricao":None,
               "_PREV_Descricao":"Rua 8 vicente pires - casa condomínio! 4qts 4 suítes. lote 800m2. closet. janelas E portas na esquadria de alumínio. lavabo. sala pé direito duplo ampla. cozinha americana ampla. armários planejados na cozinha E churrasqueira. porta princial C/ fechadura digital. piso em porcelanato de altíssimo padrão. projeto de iluminação em fita de led. ar condicionado em todos os ambientes. área de serviço independente. depósito. gás canalizado. churrasqueira gourmet. banheiro de apoio do lazer. lazer: piscina pastilhada C/ cascata, churrasqueira E fire place. Pergolado. jardinagem. quintal gramado. casa solta dos dois lados. iptu (cessão de direto) aceita permuta! Observações: Valor de venda sujeito a alteração sem aviso prévio. Valores condominiais podem sofrer alterações; portanto, devem ser confirmados pelo interessado junto à administradora do condomínio, preferencialmente no dia da visita. Agende sua visita pelos telefones: (61) Ver dados / (61) 9 Ver dados - WhatsApp. *corretores de plantão* (61) 9 Ver dados - Túlio Rios - Creci-df 22. 578. (61) 9 Ver dados - Ernando - Creci-df 24. 287. Espaço Imobiliário - Creci-df 19. 825 cj. \"O seu espaço, do seu jeito\" - 22/06/2024",
               "Link":None,
               "_PREV_Link":"https://www.wimoveis.com.br/propriedades/rua-8-vicente-pires-casa-em-condominio-2974021899.html"
            },
            {
               "_STATUS":"ADDED",
               "Position":"5",
               "Valor":"R$ 1.450.000",
               "Condominio":"R$ 480 Condominio",
               "Titulo":"Condomínio Ecológico Parque do Mirante 0",
               "Local":"Setor Habitacional Tororo, Brasília",
               "Area":"562 m² tot.",
               "Quartos":"3 quartos",
               "Banheiro":"4 ban.",
               "Garagens":"2 vaga",
               "Descricao":"Casa à venda no Condomínio Ecológico Parque do Mirante, Jardim Botânico/df. Com 236, 67m² de área construída, esse imóvel está novo e desocupado. Possui ambientes amplos, com boa iluminação natural e extensa área verde. Ideal para você que busca um imóvel novo. Além disso, o condomínio oferece portaria 24 horas, ronda, área verde e lazer. Características do imóvel: - Sala ampla. - Cozinha ampla com bancada em granito. - 3 suites. - Banheiro social. - Área de serviço. - 2 vagas cobertas. aceita financiamento. A área do imóvel anunciado é uma estimativa e deverá ser confirmada junto à certidão de ônus do imóvel ou na Secretaria da Fazenda do df. Valores e condições sujeitos a alteração sem prévio aviso. - 23/06/2024",
               "Link":"https://www.wimoveis.com.br/propriedades/qd-02-3-suites-imovel-novo-condominio-fechado-2995911652.html"
            },
            {
               "_STATUS":"REMOVED",
               "Position":None,
               "_PREV_Position":"6",
               "Valor":None,
               "_PREV_Valor":"R$ 150.000",
               "Condominio":None,
               "_PREV_Condominio":"R$ 200 Condominio",
               "Titulo":None,
               "_PREV_Titulo":"Ed. Onix Center",
               "Local":None,
               "_PREV_Local":"Aguas Norte, Águas Claras",
               "Area":None,
               "_PREV_Area":"30 m² tot.",
               "Quartos":None,
               "_PREV_Quartos":"1 quartos",
               "Banheiro":None,
               "_PREV_Banheiro":None,
               "Garagens":None,
               "_PREV_Garagens":None,
               "Descricao":None,
               "_PREV_Descricao":"Apartamento Kitnet - Edifício Onix - Mobiliado -Águas Claras. Excelente oportunidade de investimento! Apartamento kitnet à venda no bairro Norte (Águas Claras) . Com 1 Dormitório, 1 Banheiro e uma área privativa de 30m², este imóvel é perfeito para quem busca praticidade e conforto. Inclui: - Fogão. - Microondas. - Geladeira. - Filtro de Água Soft. - Armários na cozinha. - Cabideiro e prateleiras no closet. - Rack e Painel. - Cama. não inclui: tv, Lava e seca e Ar condicionado. Localizado em uma região com fácil acesso a farmácias, praças, supermercados e transporte público, este apartamento é ideal para quem deseja otimizar o tempo no dia a dia. Além disso, o condomínio oferece toda a infraestrutura necessária para garantir o seu bem-estar e segurança. Não perca essa oportunidade de adquirir o seu próprio espaço na região mais valorizada de Brasília. Comprar apartamento kitnet no bairro Norte (Águas Claras) nunca foi tão fácil. Aproveite essa chance única de conquistar o seu próprio cantinho e viver com praticidade e comodidade. Estamos aqui para te auxiliar em todo o processo de aquisição do imóvel dos seus sonhos. Esperamos por você! Whatsapp: (61) Ver dados. As informações estão sujeitas a alterações. Consulte o corretor responsável.",
               "Link":None,
               "_PREV_Link":"https://www.wimoveis.com.br/propriedades/apartamento-kitnet-edificio-onix-mobiliado-aguas-2996065353.html"
            },
            {
               "_STATUS":"ADDED",
               "Position":"6",
               "Valor":"R$ 1.160.000",
               "Condominio":"R$ 700 Condominio",
               "Titulo":"Rua 35",
               "Local":"Aguas Sul, Águas Claras",
               "Area":"145 m² tot.",
               "Quartos":"3 quartos",
               "Banheiro":"2 ban.",
               "Garagens":"2 vaga",
               "Descricao":"Residencial Sevilha. Cobertura duplex - Todo reformado. Completo em armários. com 03 quartos sendo um suíte. sala ampla, 2 ambientes. Sala de Tv/home. banheiro social. cozinha com armários. área de serviço com armários, Área de lazer privativa. churrasqueira, hidromassagem, 2 vagas de garagem coberta, Condomínio com lazer completo, Área gourmet. Churrasqueira. Salão de festas. Brinquedoteca. Salão de jogos. Sauna. mini mercado 24 hs. Portaria 24hs. localização privilegiada na parte alta de águas claras, próximo a comercio amplo e estação do metrô. - 21/06/2024",
               "Link":"https://www.wimoveis.com.br/propriedades/residencial-sevilha-cobertura-duplex-reformado-3-2997480120.html"
            },
            {
               "_STATUS":"REMOVED",
               "Position":None,
               "_PREV_Position":"7",
               "Valor":None,
               "_PREV_Valor":"R$ 520.000",
               "Condominio":None,
               "_PREV_Condominio":"R$ 611 Condominio",
               "Titulo":None,
               "_PREV_Titulo":"Quadra 101 Residencial Eliane Fleury",
               "Local":None,
               "_PREV_Local":"Aguas Norte, Águas Claras",
               "Area":None,
               "_PREV_Area":"62 m² tot.",
               "Quartos":None,
               "_PREV_Quartos":"2 quartos",
               "Banheiro":None,
               "_PREV_Banheiro":"2 ban.",
               "Garagens":None,
               "_PREV_Garagens":"1 vaga",
               "Descricao":None,
               "_PREV_Descricao":"Quadra 101 2 quartos 1 suíte 1 vaga 62m² Eliane Fleury nascente. Dentro de quadra - Nascente - Vista para Praça. Traga sua família para conhecer esse excelente imóvel! Apartamento com 62m² de área privativa. 6º andar; Ampla sala em dois ambientes com varanda; Cozinha com armários; Área de serviço; 2 quartos sendo 1 suíte; Banheiro social. Condomínio com lazer: Salão de festas, churrasqueira, quadra poliesportiva, playground, sauna, academia, piscina aquecida, espaço gourmet, brinquedoteca, salão de jogos. Comercio Local: Escolas, Restaurantes. Drogarias. Atacadão Dia a Dia. Aguardamos sua visita. Frutuosa Regino. 61 Ver dados. creci df Ver dados. Amilcar Juliano. 61 Ver dados. creci df 28850",
               "Link":None,
               "_PREV_Link":"https://www.wimoveis.com.br/propriedades/quadra-101-2-quartos-1-suite-1-vaga-62m-eliane-2996289945.html"
            },
            {
               "_STATUS":"ADDED",
               "Position":"7",
               "Valor":"R$ 890.000",
               "Condominio":None,
               "Titulo":"Quadra Qms 18 6680",
               "Local":"Setor De Mansões De Sobradinho, Sobradinho",
               "Area":"1000 m² tot.",
               "Quartos":"4 quartos",
               "Banheiro":"5 ban.",
               "Garagens":"6 vaga",
               "Descricao":"Excelente Casa Alto padrão, localizada no qms 18 Setor de Mansões - Sobradinho. Casa com 1000m² de terreno. - 4 quartos com armários sendo 3 quartos com suíte. - Sala ampla. - 1 Cozinhas com armários planejados. - Banheiro social com box. - área de serviço. - Piscina aquecida. - Academia. - Espaço gourmet. - Canil. - Piso no porcelanato. Comércio local próximo. Não perca a oportunidade de conhecer esse sonho, faça agora mesmo o seu cadastro e agende uma visita! Entre em contato para mais informações sobre o imóvel - (61) Ver dados / (61) 9 Ver dados. Visite também nosso Facebook e Instagram: @simovelimobiliaria. creci-df: Ver dados - 23/06/2024",
               "Link":"https://www.wimoveis.com.br/propriedades/excelente-casa-alto-padrao-localizada-no-qms-18-setor-2996151848.html"
            },
            {
               "_STATUS":"CHANGED",
               "Position":"8",
               "_PREV_Position":"4",
               "Valor":"Consultar preço",
               "Condominio":"Consultar preço",
               "Titulo":"SQSW 500 Bloco Q, Sudoeste, Brasília",
               "Local":"Sudoeste, Brasília",
               "Area":"1 plan.",
               "Quartos":"4 quartos",
               "Banheiro":None,
               "Garagens":None,
               "Descricao":"Seja bem-vindo(a) ao Residencial Safira, 04 Suítes, localizado na mais nova Quadra residencial do Setor Sudoeste, a Quadra 500: Preciosidade em cada detalhe. Um novo empreendimento com a assinatura da solidez, segurança e qualidade construtiva Emplavi, há 42 anos construindo histórias felizes, com mais de 31. 000 imóveis entregues no prazo. Entrega em 2024! últimas unidades. Localizado em um dos endereços mais nobres do Plano Piloto e uma das vistas mais deslumbrantes do horizonte de Brasília, o Residencial Safira harmoniza uma arquitetura imponente de linhas arrojadas e design contemporâneo, convergindo modernidade, requinte e altíssimo padrão, com inovações tecnológicas de última geração, em um harmonioso conjunto arquitetônico completo e diferenciado, que reflete a evolução contínua dos empreendimentos Emplavi, traduzindo um estilo de vida único, dinâmico e de muita personalidade em cada detalhe, que se reflete em ambientes comuns inteligentes, versáteis e luxuosos e lazer completo e diferenciado, promovendo uma experiência inigualável de viver cercado de conforto, tranquilidade e mais conectado com seu bem-estar. São modernos apartamentos de alto padrão, com 04 suítes e 4 vagas na garagem, com metragens que variam de 175, 34m² a 197, 60m², distribuídos em espaços inteligentes, versáteis e perfeitamente integrados e planejados para enriquecer o seu dia a dia, com soluções que traduzem um estilo dinâmico de viver a vida em constante movimento, sem contudo, abrir mão de momentos únicos de puro relaxamento e convívio social e familiar. Exclusivo. Único. Majestoso. Conceitos que traduzem o status do seu novo endereço em Brasília. Seja bem-vindo ao Residencial Safira: preciosidade em cada detalhe. Agende uma visita com um corretor credenciado Emplavi e conheça as obras aceleradas com unidade modelo. Entrega em 2024!! últimas unidades. Unidades sujeitas a disponibilidade. Imagens meramente ilustrativas.",
               "Link":"https://www.wimoveis.com.br/propriedades/apartamento-04-suites-sqsw-500-sudoeste-2986023558.html"
            },
            {
               "_STATUS":"REMOVED",
               "Position":None,
               "_PREV_Position":"9",
               "Valor":None,
               "_PREV_Valor":"R$ 1.499.000",
               "Condominio":None,
               "_PREV_Condominio":None,
               "Titulo":None,
               "_PREV_Titulo":"Quadra 11",
               "Local":None,
               "_PREV_Local":"Sobradinho, Sobradinho",
               "Area":None,
               "_PREV_Area":"349 m² tot.",
               "Quartos":None,
               "_PREV_Quartos":"4 quartos",
               "Banheiro":None,
               "_PREV_Banheiro":"6 ban.",
               "Garagens":None,
               "_PREV_Garagens":"2 vaga",
               "Descricao":None,
               "_PREV_Descricao":"A gm Imóveis vende casa com localização privilegiada na Quadra 11 de Sobradinho-df. O que acha de adquirir um imóvel localizado em uma das regiões mais requisitadas? *distribuição do imóvel* * aceita financiamento E fgts. * área total 350M² * área útil 320M² *Excelente casa nova e moderna. * Casa 2 pavimentos de frente ao Parque Jequitibá * Sala de jantar, cozinha e churrasqueira integrada. * Sala de tv com pé direito duplo. * Uma suíte no térreo com vista para o Parque Jequitibá, banheiro com box, nicho e chuveiro. * Lavabo. * Área de serviço coberta e varal descoberto. * Escada para o segundo piso todo em granito e parapeito em vidro. * Segundo piso. * 03 suítes, sendo uma das suítes com closet e varanda com vista para Área de lazer da casa. * Todos os banheiros com box nicho em silestone e chuveiros. * Todo o piso da casa em porcelanato 120x 120. * Todos as janelas da casa em esquadrilha de alumínio. * Projeto de iluminação em led. * Piscina toda em pastilhas e iluminação. * Banheiro na área de lazer. * Depósito. * Garagem coberta para 02 carros. * Venha conhecer e surpreenda-se! Marque agora sua visita. *observações importantes* * A área do imóvel é uma estimativa e deverá ser confirmada junto à documentação do imóvel. * Somos especialistas há mais de 15 anos no mercado imobiliário. Prestamos consultoria completa para vendedores e compradores. * Fazemos avaliação de crédito e aprovamos seu financiamento bancário na Caixa Econômica Federal, sendo o imóvel passível de financiamento. * unidade grande colorado. * creci Jurídico: Ver dados. * Ligue agora (61) Ver dados / (61) Ver dados (Whatsapp) * Marque uma visita com nossos consultores. * Atendimentos de segunda-feira a sexta-feira das 08h às 18h. * Sábado das 08h às 17h.",
               "Link":None,
               "_PREV_Link":"https://www.wimoveis.com.br/propriedades/casa-4-suites-casa-nova-aceito-financiamento-61-2991333195.html"
            },
            {
               "_STATUS":"ADDED",
               "Position":"9",
               "Valor":"R$ 1.490.000",
               "Condominio":None,
               "Titulo":"SQS 303",
               "Local":"Asa Sul, Brasília",
               "Area":"110 m² tot.",
               "Quartos":"3 quartos",
               "Banheiro":"3 ban.",
               "Garagens":"1 vaga",
               "Descricao":"*my house vende* * sqs 303 lindo* *exclusividade de venda * - O apartamento possui 110M² de área util. É um apartamento espaçoso de canto, vazado, totalmente reformado, inclusive esquadrias, parte elétrica E hidráulica. Uma sala ampla para dois ambientes, três quartos, sendo uma suíte; - banheiros da suíte com ventilação natural, box de vidro E armários. Os três banheiros com bancadas em granito E mármore; - cozinha toda reformada com bancada em granito, com armários planejados, cooktop, coifa E filtro de água. área de serviço independente E dependência completa de empregada que pode ser revertida em escritório; - piso taco na sala E nos quartos E piso porcelanato na cozinha E banheiros; - ar-condicionado na sala E na suíte? Além disso tem instalação de ar-condicionado em todos os ambientes; - placas de energia fotovoltaicas instaladas E vaga fe garagem com armário; - O prédio tem belíssimo paisagismo, portaria 24 horas, elevadores E garagem renovadas. - lindo projeto de iluminação; - banheiros reformados; - armários em todos os ambientes; - cozinha repleta de armários; - uma vaga de garagem; - vista livre. Confira! Agende sua visita E faça sua proposta! *juliana galdino - Ver dados creci 21. 536. *juliana galdino - Ver dados creci 21. 536. *leide - Ver dados creci 21. 666. *lucas dourado - Ver dados creci 26. 200. *ju mahon - Ver dados creci 28. 712. *dênis - Ver dados creci 18. 700. *alexsandra - Ver dados creci 22. 591. *juliano - Ver dados creci 10. 929. *daniel - Ver dados creci 24. 419. *marcos - Ver dados creci 11. 954. *gabriel silva - Ver dados creci 26. 962. *tatiane caiado - Ver dados creci 28. 463. *samuel - Ver dados creci 28. 275. *gabriel brandão - Ver dados creci 28. 403. aqui na my house imobiliária, estamos prontos para tornar seu sonho realidade! Como correspondentes da caixa econÔmica federal E do banco de brasília (brb), oferecemos as melhores opções de financiamento para você conquistar A casa dos seus sonhos. Seu processo realizado em um lugar só!",
               "Link":"https://www.wimoveis.com.br/propriedades/sqs-303-exclusividade-lindo-vista-livre-3-2997183894.html"
            },
            {
               "_STATUS":"REMOVED",
               "Position":None,
               "_PREV_Position":"10",
               "Valor":None,
               "_PREV_Valor":"R$ 1.790.000",
               "Condominio":None,
               "_PREV_Condominio":None,
               "Titulo":None,
               "_PREV_Titulo":"Rua 10a ,10A",
               "Local":None,
               "_PREV_Local":"Vicente Pires, Vicente Pires",
               "Area":None,
               "_PREV_Area":"400 m² tot.",
               "Quartos":None,
               "_PREV_Quartos":"4 quartos",
               "Banheiro":None,
               "_PREV_Banheiro":"6 ban.",
               "Garagens":None,
               "_PREV_Garagens":"2 vaga",
               "Descricao":None,
               "_PREV_Descricao":"Ernani Nunes Consultoria Imobiliária de Luxo Apresenta! Localizada no Vicente Pires - Brasília df. Rua 10A Condomínio Topissimo com portaria 24 hs. Composta por: Linda Fachada imponente. 4 belíssimas suítes. Sala com Pé Direito Duplo. Porta Pivotante. Espaço Gourmet com churrasqueira. Piscina. Sala de tv. 6 banheiros. Piso em porcelanato acetinado. Garagem para 2 carros. Acabamentos Premium. Valor: R$ 1. 800. 000. Não aceita financiamento! As informações acima, bem como os preços dos imóveis podem sofrer alterações sem aviso prévio. Somos especialistas em imóveis nas regiões de Condomínios fechados, contando com uma equipe de Corretores altamente treinados e capacitados para melhor atendê-los, na hora de comprar e vender. Ernani nunes consultoria imobiliária creci jurídico 27 826 df. ernani nunes creci 17 921 df. whatsapp. 61 9 Ver dados Tim. 61 9 Ver dados Claro. Ver dados 64 Escritório. sites: ernaninunes. Com. Br. ernaninunes. Com. ocorretordasmansoes. Com. br. cap ernani nunes - 05/03/2024",
               "Link":None,
               "_PREV_Link":"https://www.wimoveis.com.br/propriedades/casa-alto-padrao-4-suites-lazer-completo-rua-10a-2996445044.html"
            },
            {
               "_STATUS":"ADDED",
               "Position":"10",
               "Valor":"R$ 2.750.000",
               "Condominio":None,
               "Titulo":"Setor SMDB Conjunto 5",
               "Local":"Lago Sul, Brasília",
               "Area":"2400 m² tot.",
               "Quartos":None,
               "Banheiro":None,
               "Garagens":None,
               "Descricao":"Smdb conjunto 05 - setor de mansões dom boscocolina dom boscocondomínio residencial projetado pela arquiteta Denise Zuba e construído pela Revest Engenharia em terreno de 12. 000m² de área total, composto por cinco unidades com 2. 400m² de área total, sendo 1. 919m² de área privativa para cada uma delas. Construa a casa dos seus sonhos em uma das melhores localizações do Lago Sul, com facilidades a poucos metros do condomínio: transporte para funcionários; proximidade com as melhores escolas; supermercados; farmácias; academias; bancos; lanchonetes etc. Unidade C: Valor R$ 2. 750. 000, 00 unidade D: Valor R$ 2. 750. 000, 00características do condomínio: Guarita Principal com banheiro, portaria com interfone, central de monitoramento, portão de acesso de veículos eletrônico, portão de pedestres, caixa de correios, mureta e grande frontal;Paisagismo e gramado com irrigação automatizada nas áreas comuns;Pontes de iluminação nas áreas comuns (interna e externa) ;Circulação em bloquetes de concreto e meio fio. características E vantagens da colina dom bosco: 1 A guarita de segurança da Colina, que faz ronda a cada 1h na região, podendo acompanhar o morador até a entrada do condomínio nos horários de chegada; 2 A Colina possui câmeras de segurança espalhadas na região para monitoramento 24h, o que proporciona mais segurança do que em qualquer outra;3 Entrada e saída únicas, o que proporciona mais segurança;4 Ótimas escolas próximas: (Everest, Escolas das Nações e Escola Francesa) ;5 Proximidade das Pontes Costa e Silva e jk;6 Ótimo comercial local com supermercado, farmácia, restaurantes, pizzaria, banca de revista;7 serviço de transporte de funcionários exclusivo da av. Principal até A entrada do conjunto;8 grupo de segurança dos moradores da colina com A participação do batalhão rio branco da polícia militar. Os preços, valores e informações exibidos poderão sofrer alterações sem prévio aviso e deverão ser conferidos pelos interessados na matricula do imóvel e na Secretária de Fazenda do df. Maiores informações: Anderson Bordalo Ver dadosDiego Gomes Ver dadosBruno Frechiani Ver dadosSuami Lins Ver dadosGlauber Garbim Ver dadosViviane Lacerda Ver dadosGisella Bordalo Ver dadosAline Bergamaschine - Ver dados Flávia Landim Ver dadosEdson Júnior - Ver dadosEkaterina Sukhoverkhova - Ver dadosFernanda Anjos - Ver dadosÉdla Piau - Ver dadosTatiane Smith - Ver dadosBordalo prime Imobiliária Ver dadosCodigo anúncio: villaVer dados - Ver dados",
               "Link":"https://www.wimoveis.com.br/propriedades/projeto-denise-zuba.-2977480265.html"
            },
            {
               "_STATUS":"REMOVED",
               "Position":None,
               "_PREV_Position":"11",
               "Valor":None,
               "_PREV_Valor":"R$ 575.500",
               "Condominio":None,
               "_PREV_Condominio":"R$ 860 Condominio",
               "Titulo":None,
               "_PREV_Titulo":"QRSW Quadra 2,B,",
               "Local":None,
               "_PREV_Local":"Sudoeste, Brasília",
               "Area":None,
               "_PREV_Area":"62 m² tot.",
               "Quartos":None,
               "_PREV_Quartos":"2 quartos",
               "Banheiro":None,
               "_PREV_Banheiro":"1 banheiro",
               "Garagens":None,
               "_PREV_Garagens":"1 vaga",
               "Descricao":None,
               "_PREV_Descricao":"Apartamento No Sudoeste Econômico 62M² Reformado. - Lindo apartamento todo reformado e repleto de armários, localizado na quadra qrsw 02 com vista livre, no 3. º andar, para clientes exigentes que procuram por tranquilidade e localização privilegiada! - Pão de Açúcar (350mts), 750mts Bosque Sudoeste), (400mts terminal rodoviário do Cruzeiro Novo) e 2km do Parque da Cidade. - 02 quartos com vista livre. - Banheiro social reformado. - Sala de estar conjugada com a cozinha americana. - Vazado e com 2 varandas no blindex. - 62m² de área útil e 68m² de área total com as varandas. - Armários em todos os cômodos. - Cozinha com bancada de granito e planejada repleta de armários. - Depósito externo para guardar utensílios. - O imóvel está impecável! - Venha conhecer e se encantar com esse Lindo Projeto. - valor: 575. 000 Mil. - consulte o corretor responsável / Exclusividade e aberto a parcerias! - Aceita financiamento Bancário. - marcelo arruda - Creci 25. 628. 61 - Ver dados. - Escritório re/max virtus imobiliária. 61 - Ver dados. - Creci 25. 628",
               "Link":None,
               "_PREV_Link":"https://www.wimoveis.com.br/propriedades/apartamento-2-quartos-sudoeste-economico-2975128184.html"
            },
            {
               "_STATUS":"ADDED",
               "Position":"11",
               "Valor":"R$ 605.000",
               "Condominio":"R$ 550 Condominio",
               "Titulo":"rua babaçu lote 3",
               "Local":"Aguas Sul, Águas Claras",
               "Area":"68 m² tot.",
               "Quartos":"2 quartos",
               "Banheiro":"3 ban.",
               "Garagens":"1 vaga",
               "Descricao":"Art Life Design é um condomínio sofisticado, ideal para quem é moderno e deseja conforto e comodidade. Com mais de 20 itens de lazer para adultos, jovens e crianças, Art Life Design é sinônimo de uma vida prática e requintada. Com localização privilegiada e estratégica, conta com várias entradas e saídas fáceis, perto de instituições de ensino, supermercados, hospital Brasília, a poucos metros da estação de metrô Águas Claras, próximo ao novo parque público, bares, restaurantes e padarias. O imóvel está disposto atualmente: - Sala ampla; - Cozinha americana; - Varanda gourmet; - Área de serviço; - Banheiro de apoio; - 2 Quartos sendo 1 Suíte; - Banheiro social; - 1 Vaga de garagem; Diferenciais: - Reformado; - Móveis planejados em todos os ambientes; - Varanda Gourmet; - Piso laminado; - Andar alto; Lazer: - Piscina adulto; - Piscina infantil; - Piscina com raia; - Playground; - Quadra de areia; - Parede de escalada; - spa com sauna; - 2 Churrasqueiras; - Salão de festas adulto com terraço; - Salão de festas infantil; - Salão de festas panorâmico; - Sala de jogos adolescente; - Sala de jogos adulto; - Home cinema; - Espaço gourmet; - Quadra poliesportiva; - Brinquedoteca; - Garage band; - Rampa de skate; Agende sua visita: Alden Yamane. (61) Ver dados. creci J Ver dados. creci 27793. cnai 42505",
               "Link":"https://www.wimoveis.com.br/propriedades/rua-babacu-art-life-design-2-quartos-1-suite-2997457840.html"
            },
            {
               "_STATUS":"UNCHANGED",
               "Position":"12",
               "Valor":"R$ 2.774.103",
               "Condominio":"R$ 2.774.103",
               "Titulo":"SQNW 304 Bloco F",
               "Local":"Noroeste, Brasília",
               "Area":"5 plan.",
               "Quartos":"4 quartos",
               "Banheiro":None,
               "Garagens":None,
               "Descricao":"High design - Apartamento à venda no Setor Noroeste com 4 Suítes. Traços simples, beleza atemporal. Luxuosas intervenções na biofilia. Projeção com Vista Definitiva; Apartamentos Realmente Vazados; 4 Suítes com Plantas Personalizáveis; Biofilia integrada a fachada; O maior vão de sala do Noroeste. O empreendimento High Design apresenta uma perfeita integração entre espaços, eliminando barreiras visuais para uma experiência única. As unidades de luxo oferecem 4 quartos (4 suítes), variando de 184, 01m² a 246, 25m², enquanto as coberturas duplex abrangem de 360, 96m² a 493, 87m². Este projeto destaca-se pelo maior vão de sala no Noroeste, proporcionando apartamentos verdadeiramente arejados com uma ventilação cruzada espetacular. A amplitude, a ausência de pilares entre varanda e sala, a cozinha gourmet em ilha e as múltiplas opções de uso do espaço conferem uma sofisticação incomparável, fazendo toda a diferença na rotina diária e ao receber visitas. A linha Design, além disso, incorpora conceitos marcantes como a biofilia, a conexão com a natureza e o apreço pelo vivo. Cores e texturas que refletem a luz natural são priorizadas, visando o bem-estar e conforto emocional. A contemporaneidade dos projetos é evidente, unindo aspectos artísticos a tendências, praticidade, linhas simples e tons neutros, com toques de detalhes coloridos. Cada novo empreendimento traz otimizações únicas, graças a plantas personalizadas. Os layouts são singulares, proporcionando aos compradores a sensação de residir em um imóvel concebido exclusivamente para eles, mantendo os mais elevados padrões de sofisticação. A presença de tecnologia é notável em detalhes como elevadores exclusivos por apartamento, botão antipânico, tomadas para carro elétrico e garagem com design arrojado, incluindo teto forrado e diversas outras inovações exclusivas. As áreas comuns são diversificadas, incluindo Brinquedoteca, Playground, Espaço Teen, Salão de Festas, Guarita com vidros blindados, Sala para Motoristas, Piscina Coletiva, Academia, Espaço Gourmet, Car Wash e Espaço Bike, proporcionando uma experiência completa para os moradores. Previsão de entrega: Dezembro/2024. Visite a Central de Vendas ecap: clnw 02/03 Bloco C. unidades. • Fechadura eletrônica, que dispensa o uso de chaves. • Sistema All Connect: infraestrutura para cabeamento estruturado de dados e voz, sinal de tv, telefone e internet banda larga, permitindo flexibilidade dos pontos de instalação das unidades autônomas. • Sistema de tv preparado para receber transmissões abertas e fechadas. • Tomada usb nas salas, nos quartos e na cozinha. • Infraestrutura para receber cabeamento estruturado para internet por link dedicado em todos os apartamentos. • Infraestrutura para instalação de ar condicionado modelo Inverter nas salas e nas suítes, com laje técnica para as condensadoras. • Infraestrutura (tubulação seca) para automação de sonorização na sala, na sala íntima e na suíte master. • Infraestrutura (tubulação seca) para automação de câmeras, iluminação, ar condicionado e cortinas na sala, no hall íntimo, na sala íntima, na cozinha e nos quartos. • Botão antipânico na suíte master. • Ponto de água para geladeira, lava-louça e filtro na cozinha. • Água quente nas torneiras dos banheiros e da cozinha (exceto lavabo, banheiro e área de serviço). • Laje plana maciça para garantir a Norma de Desempenho no quesito “Acústica”. • Sensor de vazamento de gás na cozinha. • Previsão para individualização de água e gás. • Banheiro da suíte master com previsão para dois chuveiros de teto. • Ralo linear nos boxes dos banheiros sociais. • Apartamentos realmente vazados: mais iluminação e ventilação natural. • Piscinas das coberturas privativas entregues com previsão para aquecimento. áreas comuns. • Leitor biométrico nos halls do pilotis, com opção de cartão. • Elevador privativo com sistema de segurança e código de acesso: apenas o morador ou a pessoa autorizada poderá acessar o andar desejado. • Sistema de segurança com monitoramento por câmeras instaladas e visualização via celular. • Infraestrutura para replicar o sinal de wi-fi nas áreas comuns do condomínio. • Sistema de geração de energia fotovoltaica, para redução de valor na conta de energia do condomínio. • Forro acústico no espaço gourmet, no salão de festas, no fitness e na brinquedoteca, atendendo ao item “Acústica” da Norma de Desempenho. • Equipamentos de ar condicionado de baixo consumo instalados no fitness, salão de festas, brinquedoteca, espaço teen e no espaço gourmet. • Piscina climatizada na cobertura coletiva. • Torneiras com fechamento automático. • Piso de porcelanato específico para as áreas descobertas. • Tomadas usb no fitness, no espaço gourmet e no salão de festas. • Sistema de sonorização no fitness e no espaço gourmet. • Ponto para recarregamento de bicicletas elétricas. • Gerador de energia para elevadores, bombas, portão da garagem, iluminação nas áreas comuns, caso haja descontinuidade de fornecimento pela concessionária (Neoenergia). • Sensor de vazamento de gás nos halls de serviço. • Automação, controle e supervisão predial (consumo de energia, bombas e iluminação). • Sistema de irrigação automatizado. • Sensor de presença setorizado nos halls e na garagem - muito mais economia de energia. • Infraestrutura preparada para reaproveitamento de águas cinzas. • Um ponto de carregador elétrico rápido para carros. • Subsolos com teto forrado com gesso acartonado e piso da garagem com pintura epóxi. • Iluminação das áreas comuns 100% com led.",
               "Link":"https://www.wimoveis.com.br/propriedades/apartamento-noroeste-high-design-2962565200.html"
            },
            {
               "_STATUS":"REMOVED",
               "Position":None,
               "_PREV_Position":"13",
               "Valor":None,
               "_PREV_Valor":"R$ 2.700.000",
               "Condominio":None,
               "_PREV_Condominio":"R$ 550 Condominio",
               "Titulo":None,
               "_PREV_Titulo":"Rua Rua 6",
               "Local":None,
               "_PREV_Local":"Vicente Pires, Vicente Pires",
               "Area":None,
               "_PREV_Area":"800 m² tot.",
               "Quartos":None,
               "_PREV_Quartos":"4 quartos",
               "Banheiro":None,
               "_PREV_Banheiro":"6 ban.",
               "Garagens":None,
               "_PREV_Garagens":"3 vaga",
               "Descricao":None,
               "_PREV_Descricao":"Luxuosa casa em condomínio fechado na rua 06 Vicente Pires. Toda na marcenaria. Condomínio alto padrão, próximo à escolas, mercados, padaria. ampla sala pdd, com pele de vidro em esquadria de alumínio, 3 ambientes, projeto luminotécnico em todo imóvel. Lavabo. 4 suítes amplas, sendo 03 com closet, completa em armários, e a master com 2 chuveiros e 2 cubas. Banheiros em fino acabamento com bancadas em mármore, chuveiros alto padrão. Cozinha tipo americano com extensa bancada em granito marrom absoluto, completa em armários. Lote 800 m² Área construída 500m² Espaço gourmet com churrasqueira e banheiro masculino e feminino integrado à piscina. Piscina toda em pastilha, aquecida com sauna interligada, Lavanderia. Casa solta no lote. Garagem para 06 carros. 06 banheiros. Paisagismo na frente da casa. cj 28. 770 ->. Serra Negra Imobiliária e empreendimentos. Avaliamos e vendemos seu imóvel em todo o df! Estuda proposta. Todos os valores anunciados podem ser alterados sem prévio aviso. Acesse nossa rede social: @serranegraimobiliariadf - 12/03/2024",
               "Link":None,
               "_PREV_Link":"https://www.wimoveis.com.br/propriedades/casa-alto-padrao-4-quartos-800-m-lazer-completo-2994101325.html"
            },
            {
               "_STATUS":"ADDED",
               "Position":"13",
               "Valor":"R$ 1.560.000",
               "Condominio":"R$ 1.152 Condominio",
               "Titulo":"SQSW 105 BLOCO H 1º ANDAR",
               "Local":"Sudoeste, Brasília",
               "Area":"153 m² tot.",
               "Quartos":"3 quartos",
               "Banheiro":"3 ban.",
               "Garagens":"1 vaga",
               "Descricao":"Belíssimo apartamento de 107m², canto, são 3 quartos, com 1 suíte, vista livre, voltado para o jardim, todo reformado, piso porcelanato acetinado 1x1, projeto de iluminação em todos os ambientes, cozinha com muitos armários novos, quarto principal com closet, banheiros reformados, escritório. Iptu: 2. 533, 73. Condomínio: 1. 152, 00",
               "Link":"https://www.wimoveis.com.br/propriedades/raridade-no-sudoeste-2997609809.html"
            },
            {
               "_STATUS":"REMOVED",
               "Position":None,
               "_PREV_Position":"14",
               "Valor":None,
               "_PREV_Valor":"R$ 760.000",
               "Condominio":None,
               "_PREV_Condominio":"R$ 846 Condominio",
               "Titulo":None,
               "_PREV_Titulo":"Rua 28 Norte Águas Claras Residencial Via Paradiso",
               "Local":None,
               "_PREV_Local":"Aguas Norte, Águas Claras",
               "Area":None,
               "_PREV_Area":"96 m² tot.",
               "Quartos":None,
               "_PREV_Quartos":"3 quartos",
               "Banheiro":None,
               "_PREV_Banheiro":"3 ban.",
               "Garagens":None,
               "_PREV_Garagens":"1 vaga",
               "Descricao":None,
               "_PREV_Descricao":"Rua 28 Norte - Residencial Via Paradiso - Águas Claras. Apartamento Reformado de 96m² de área últil; Na melhor Localização de Águas Claras, próximo à saída de Águas Claras para Taguatinga, na rua da Padaria Bonapan, restaurante Madero e ao lado do Shopping Felicitá. Decrição detalhada do Apartamento: - Sala ampla composta por 02 ambientes sala de estar e sala de jantar com lustre, espelho, cristaleira, decoração 3D e projeto de iluminação impecável, e piso no vinílico; - Varanda ampla com projeto de decoração 3D na parede, vista livre para o futuro Parque Central de Águas Claras; - São 03 quartos reformados sendo 01 suíte, no piso vinílico, armário planejado e excelente ventilação; - Escritório repleto de armários planejados, escrivaninha, nichos e prateleira de excelente qualidade (podendo ser ultilizado como o 4° quarto) ; - Banheiro de Serviço equipado com ventilação natural; - Cozinha ampla composta por 2 ambientes, armários planejados, torre quente com forno embutido e microondas embutido, coifa e piso na cerâmica; - Área de serviço integrada com ótima ventilação e vista livre para o futuro Parque Central; - Banheiro Social grande reformado, box blindexbancada em celestone, projeto de iluminação, espelho e parede com decoração em pastilhas; - 01 Vaga de garagem no subsolo com armário, ao lado do elevador (a melhor vaga) ; O Residencial Via Paradiso tem Lazer Completo! Composto por: - 02 Piscinas com raias Aquecidas (adulto e infantil) ; - Academia Reebok Fitness Center com assessoria esportiva profissional, acompanhamento dos professores de educação física nos períodos da manhã, tarde e noite, contempla um rol de atividades, natação, hidroginástica, musculação, crossfit, futebol de salão, vôlei, capoeira etc. (com tv de plasma 42) ; - Quadra Poliesportiva; - Rampa de Skate Park; - 04 Churrasqueiras; - Sauna; - spa área com hidromassagem; - 02 Salões de festas panorâmicos com terraço (capacidade para 120 e 90 convidados, 01 salão é integrado à churrasqueira) ; - Playground; - Home Cinema com leitor de blu ray; - Sala de estudos; - Espaço kids; - Espaço gourmet e pizza point (com tv de plasma 42) ; - Lan House com monitor; - Hall principal com área especial de embarque/desembarque, recepção confortável etc; - Portaria 24 Horas (com dois porteiros full time) ; - Circuito Interno de Monitoramento (cftv) . Valor do Investimento: R$ 760. 000. Valor do Condomínio: R$ 846, 00. Agende sua visita! Juliana Corrêa. 61 Ver dados (WhatsApp) Corretora de imóveis - Perita Avaliadora - Corretora Prêmiada no Distrito Federal. Creci nº Ver dados. Viviane Bijos. 61 Ver dados (WhatsApp) Corretora de imóveis - Perita Avaliadora - Corretora Prêmiada no Distrito Federal. Creci nº Ver dados. gestão exclusiva remax - Corretores Fazemos Parcerias!",
               "Link":None,
               "_PREV_Link":"https://www.wimoveis.com.br/propriedades/apartamento-reformado-3-quartos-1-escritorio-1-suite-2996604222.html"
            },
            {
               "_STATUS":"ADDED",
               "Position":"14",
               "Valor":"R$ 695.000",
               "Condominio":"R$ 615 Condominio",
               "Titulo":"Quadra 101 1003",
               "Local":"Águas Claras, Brasília",
               "Area":"82 m² tot.",
               "Quartos":"3 quartos",
               "Banheiro":"3 ban.",
               "Garagens":"1 vaga",
               "Descricao":"Quadra 101 - Tie Residencial Clube, Águas Claras/df. Apartamento reformado, nascente, proporcionando uma vista desimpedida e situado em um andar alto, apresenta-se da seguinte forma: Uma sala espaçosa, ideal para dois ambientes, revestida com piso flutuante que confere elegância ao espaço. A iluminação foi meticulosamente planejada, destacando ainda mais a beleza do ambiente. Detalhes em gesso foram estrategicamente inseridos nas paredes e no teto, agregando charme e sofisticação. Além disso, a sala dispõe de acesso direto à varanda, ampliando a sensação de espaço e proporcionando um local perfeito para momentos de relaxamento. O lavabo, também objeto de uma reforma cuidadosa, exibe um papel de parede que adiciona um toque de personalidade ao ambiente. A iluminação foi especialmente planejada para criar uma atmosfera aconchegante e convidativa. Um hall de circulação conduz aos três dormitórios do apartamento, distribuídos da seguinte maneira: O Quarto I, originalmente a dependência de empregada, foi revertido em um ambiente funcional, equipado com um roupeiro e um depósito, oferecendo espaço de armazenamento adicional de forma prática e organizada. O Quarto ii é uma suíte que ostenta armários planejados, proporcionando amplo espaço para guardar pertences de forma organizada. Além disso, o ambiente conta com ar condicionado para garantir o conforto térmico durante todo o ano. Uma cabeceira fixa adiciona um toque de elegância à decoração, enquanto o banheiro completo oferece comodidade e praticidade. O Quarto iii também apresenta armários planejados, complementados por prateleiras que maximizam o espaço disponível. Uma luminária de teto equipada com ventilador garante conforto durante os dias mais quentes, tornando este quarto um espaço acolhedor e funcional. Um banheiro social completo, equipado com armários, atende às necessidades dos moradores e de seus convidados com praticidade e bom gosto. O apartamento inclui ainda uma vaga de garagem, garantindo comodidade e segurança para os residentes. Lazer: Salão de festas, sauna masculina e feminina, piscina semiolimpica, academia e pista interna de Cooper, brinquedoteca, vagas rotativas no Pilotis, churrasqueiras e muito mais. Atenção** Informamos que não recebemos ou autorizamos que nenhum corretor parceiro receba sinal ou pagamento de compra de imóveis. Os devidos pagamentos deverão ser efetuados nas contas e nos termos estabelecidos no instrumento de compra e venda Assinado e reconhecido em cartório. * A área do imóvel é uma estimativa e deverá ser confirmada junto a Certidão de Ônus do imóvel ou cessão de direitos, se não se tratar de bem a ser vendido como coisa certa e discriminada. - 23/06/2024. Bruno Arthur: (61) Ver dados",
               "Link":"https://www.wimoveis.com.br/propriedades/quadra-101-apartamento-com-3-quartos-nascente-2993613960.html"
            },
            {
               "_STATUS":"REMOVED",
               "Position":None,
               "_PREV_Position":"15",
               "Valor":None,
               "_PREV_Valor":"R$ 2.640.000",
               "Condominio":None,
               "_PREV_Condominio":"R$ 500 Condominio",
               "Titulo":None,
               "_PREV_Titulo":"Rua 4",
               "Local":None,
               "_PREV_Local":"Vicente Pires, Vicente Pires",
               "Area":None,
               "_PREV_Area":"640 m² tot.",
               "Quartos":None,
               "_PREV_Quartos":"4 quartos",
               "Banheiro":None,
               "_PREV_Banheiro":"6 ban.",
               "Garagens":None,
               "_PREV_Garagens":"4 vaga",
               "Descricao":None,
               "_PREV_Descricao":"Ernani Nunes, o Corretor das Mansões apresenta!! Excelente Mansão em Vicente Pires. Localizado na Rua 4, dentro de condomínio de Alto Padrão, a 800m da eptg. Portaria 24h, Nascente. Obra feita sob Laudo de Sondagem do solo, Projeto de cálculo estrutural registrado no crea/df. Projetos arquitetônicos quadratti arquitetura e oitoquatro arquitetura, com 14m de frente, 46 de fundo. Composta por: Área do Lote: 640 m² Área construída da casa: 400 m² 460 m² de área total. Fachada Moderna. Porta de entrada com 4, 70 m de altura e 1. 55 m largura de alumínio e vidro temperado, fechadura digital e vídeo porteiro. Sala pé direito duplo. 4 suítes com Ar condicionado inverter lg 9000 bts. Suíte principal com closet. Lavabo. Piso no Portinari acetinado 120 cm x 120 cm e no biancogres. Rodapé com altura de 20 cm. Cozinha completa com ilha, balcão em granito e armários, eletrodomésticos da marca Brastemp (freezer, geladeira, fogão, coifa, forno elétrico, microondas) Louças e metais na marca Roca e Incepa. Varanda gourmet com churrasqueira a carvão, climatizada com ar condicionado Ver dados Btus inverter, com portas em esquadrias de aluminium e vidro temperado. 6 banheiros no total com box e espelhos. Lavanderia completa com armários. Pergolado, Portão eletrônico, esquadrias em aluminium. A casa será entregue com armários nos seguintes cômodos: No Closet do quarto de casal, todos os banheiros, wc, varanda Gourmet, cozinha, despensa, e área de serviço. Lazer com: Piscina aquecida com prainha e com iluminação. Fireplace. Depósito. Área verde. -Documentação com iptu individualizado e escritura de cessão de direitos. Valor: R$ 2. 640. 000, 00. Condomínio: R$ 370, 00. Zelador/porteiro: de 7h as 12h. Zelador/porteiro: de 13h as 17h. Porteiro: de 20h as 5h. não aceita financiamento E nem fgts. As informações acima, bem como os preços dos imóveis podem sofrer alterações sem aviso prévio. Somos especialistas em imóveis nas regiões de Condomínios fechados, contando com uma equipe de Corretores altamente treinados e capacitados para melhor atendê-los, na hora de comprar e vender. Ernani nunes consultoria imobiliária creci jurídico 27 826 df. ernani nunes creci 17 921 df. whatsapp. 61 9 Ver dados Tim. 61 9 Ver dados Claro. Ver dados 64 Escritório. sites: ernaninunes. Com. Br. ernaninunes. Com. ocorretordasmansoes. Com. br. cap ernani nunes",
               "Link":None,
               "_PREV_Link":"https://www.wimoveis.com.br/propriedades/mansao-4-suites-lazer-completo-e-planejados-em-vicente-2979694656.html"
            },
            {
               "_STATUS":"ADDED",
               "Position":"15",
               "Valor":"R$ 1.600.000",
               "Condominio":"R$ 150 Condominio",
               "Titulo":"Sha Conjunto 4 Chácara 60 ,60",
               "Local":"Arniqueiras, Águas Claras",
               "Area":"400 m² tot.",
               "Quartos":"3 quartos",
               "Banheiro":"4 ban.",
               "Garagens":"2 vaga",
               "Descricao":"Ernani Nunes O corretor das mansões, apresenta! Belíssima Casa no Conjunto 4 de Arniqueiras. Lazer Completo e jardim suspenso! Será entregue com armários nos quartos, closet, banheiro E cozinha. não aceita financiamento E nem fgts. estuda proposta de permuta até 50% do valor do imóvel. Composta por: 3 suítes, sendo 1 Suíte Master com Closet, banheiro com 2 chuveiros e duas pias; Porta principal em vidro preto com 5, 5m de altura; Preparação para ar em todos os ambientes; Sala de estar com pé direito duplo; Lavabo; Cozinha conjugada com Espaço Gourmet e churrasqueira; Janelas e portas em esquadrias de alumínio; Piscina de alvenaria com pastilhas; Churrasqueira. Ilha e bancada. Terreno 400 m² Área construída 280 m². Valor: R$ 1. 600. 000, 00. não aceita financiamento E nem fgts. estuda proposta de permuta até 50% do valor do imóvel. As informações acima, bem como os preços dos imóveis podem sofrer alterações sem aviso prévio. Ernani nunes consultoria imobiliária creci jurídico 27 826 - df. ernani nunes - creci 17 921 df. whatsapp. 61 9 Ver dados Tim. 61 9 Ver dados Claro. Ver dados 64 Escritório. sites: ernaninunes. Com. Br. ernaninunes. Com. ocorretordasmansoes. Com. br. cap wesley reis - 27/05/2024",
               "Link":"https://www.wimoveis.com.br/propriedades/bela-casa-3-suites-com-closet-e-piscina-no-conj-4-de-2996445012.html"
            },
            {
               "_STATUS":"REMOVED",
               "Position":None,
               "_PREV_Position":"16",
               "Valor":None,
               "_PREV_Valor":"R$ 1.322.930",
               "Condominio":None,
               "_PREV_Condominio":"R$ 1.322.930",
               "Titulo":None,
               "_PREV_Titulo":"SQNW 303, Bloco H",
               "Local":None,
               "_PREV_Local":"Noroeste, Brasília",
               "Area":None,
               "_PREV_Area":"4 plan.",
               "Quartos":None,
               "_PREV_Quartos":"2 quartos",
               "Banheiro":None,
               "_PREV_Banheiro":"77 a 180 m² tot.",
               "Garagens":None,
               "_PREV_Garagens":None,
               "Descricao":None,
               "_PREV_Descricao":"Demartini - Seu Espaço Único e Cheio de Personalidade no Setor Noroeste! Descubra o Demartini, o melhor 2 quartos do Noroeste, um empreendimento que vai além do comum, projetado para trazer personalidade à sua vida. Com apartamentos de 2 quartos de alto padrão, incluindo uma suíte com closet, cozinha americana, sala ampla com varanda e o padrão construtivo exclusivo da Soltec, o Demartini é a escolha certa para quem busca qualidade e conforto. Plantas Versáteis: As plantas do Demartini variam de 76 a 180m², oferecendo opções que se adaptam perfeitamente às suas necessidades. Seja qual for o tamanho da sua vida, o Demartini tem a solução ideal. Localização Estratégica: Situado na sqnw 303, uma das melhores quadras do Setor Noroeste, o Demartini oferece proximidade a hipermercados, shoppings, faculdades, escolas e hospitais. Tudo pensado para otimizar a sua rotina diária. Diferenciais Exclusivos: O Demartini traz diferenciais que fazem toda a diferença. Totalmente residencial, oferece tranquilidade inigualável. A fachada revestida em granito, vidro fumê e esquadria anodizada proporcionam sofisticação. Com monitoramento por câmeras 24h, sensor de vazamento de gás nos apartamentos e Wi-Fi nas áreas de lazer, a segurança e comodidade estão garantidas. Lazer Completo: As áreas de lazer do Demartini foram pensadas para proporcionar a melhor experiência de moradia. Com Espaço Kids climatizado e monitorado via mobile, salão de festas, brinquedoteca, espaço gourmet, academia, piscina adulto e infantil, deck, churrasqueira, sauna e espaço pet, cada detalhe foi cuidadosamente planejado para você e sua família desfrutarem momentos únicos. Não espere mais, venha conhecer o Demartini e viva a vida com personalidade! Conheça o decorado na nossa Central de Vendas do Noroeste na clnw 02/03, Lote J.",
               "Link":None,
               "_PREV_Link":"https://www.wimoveis.com.br/propriedades/apartamento-noroeste-demartini-noroeste-2959066267.html"
            },
            {
               "_STATUS":"ADDED",
               "Position":"16",
               "Valor":"Consultar preço",
               "Condominio":"Consultar preço",
               "Titulo":"SQSW 500, Projeção V",
               "Local":"Sudoeste, Brasília",
               "Area":"2 plan.",
               "Quartos":"4 quartos",
               "Banheiro":None,
               "Garagens":None,
               "Descricao":"Quanto mais raro, mais valorizado. Prepare-se para viver um novo status de exclusividade! A Emplavi apresenta o Residencial Esmeralda 4 suítes Premium: seu mais novo lançamento, na melhor localização da Quadra 500 do Setor Sudoeste, em frente ao Parque das Sucupiras e com a vista mais privilegiada do horizonte da capital. Uma fusão rara de beleza, nobreza, sofisticação, requinte e funcionalidade em um conjunto arquitetônico exuberante e projetos de 4 suítes de 210, 64m² a 317, 35m² e coberturas privativas, que irão agregar um valor imensurável ao status do seu novo endereço em Brasília. Raro. Magnífico. Surpreendente. Seja bem-vindo ao Residencial Esmeralda: preciosidade em cada detalhe. Antecipe-se, cadastre-se e aproveite condições exclusivas de lançamento!",
               "Link":"https://www.wimoveis.com.br/propriedades/apartamento-cobertura-residencial-esmeralda-quadra-2995989243.html"
            },
            {
               "_STATUS":"REMOVED",
               "Position":None,
               "_PREV_Position":"17",
               "Valor":None,
               "_PREV_Valor":"R$ 499.000",
               "Condominio":None,
               "_PREV_Condominio":"R$ 497 Condominio",
               "Titulo":None,
               "_PREV_Titulo":"QI 12 CARPE DIEM 2 Quartos ,1 Suíte -Mobiliado e Decorado",
               "Local":None,
               "_PREV_Local":"Taguatinga Norte, Taguatinga",
               "Area":None,
               "_PREV_Area":"57 m² tot.",
               "Quartos":None,
               "_PREV_Quartos":"2 quartos",
               "Banheiro":None,
               "_PREV_Banheiro":"2 ban.",
               "Garagens":None,
               "_PREV_Garagens":None,
               "Descricao":None,
               "_PREV_Descricao":"A My House Imobiliária vende: Visitas: Leide Ver dados. apartamento mobiliado E decorado de 2 quartos, com lazer completo. Localização: qi 12 Carpe Diem. Características: Tamanho: 57, 75 m² Porteira Fechada. Distribuição: Quartos: 2 (1 suíte e 1 social) Banheiros: 2. Cozinha. Área de Serviço. Sala de Estar. Sala de Jantar. Varanda Gourmet. Mobília e Decoração: -Quarto Casal: Cama Queen, guarda-roupa planejado, abajur e cortinas. -Banheiro Suíte: Box em Vidro e espelho. -Quarto Social: Cama casal padrão, guarda-roupa planejado, tv de 50” e cortinas. -Sala de Jantar: Mesa com 4 cadeiras em madeira Imbuia Mel e assento em tecido Linho Champagne, aparador em madeira Imbuia Mel com jarros de -plantas decorativas, nicho em madeira ripado e espelho em bronze. -Sala de Estar: Painel em madeira branca com 4 gavetas, nicho ripado, tv de 50”, sofá de 3 lugares em tecidos Linho Champagne, 2 mesas laterais em madeira Imbuia Mel e cortinas. -Varanda: Canto Alemão em madeira e estofado em “L”, churrasqueira elétrica com armário planejado, blindex e persianas rolô -Cozinha: Geladeira duplex, armário planejado, pia em pedra mármore absolution na cor cinza, forno elétrico, fogão cooktop 4 bocas, depurador de ar, micro--ondas, bancada americana com 2 banquetas em madeira Imbuia Mel. -Área de Serviço: Armário planejado, máquina de lavar 13kg, tanque em pedra mármore absolution na cor cinza. -Valor: R$ 499. 000, 00. Este apartamento oferece uma oportunidade única com todos os móveis e eletrodomésticos necessários para uma vida confortável e está pronto para morar. Agende sua visita hoje mesmo! Aceita fgts E financiamento. Confira! Agende sua visita E faça sua proposta! Leide Ver dados whatsapp creci 21. 666. tim Ver dados creci 21. 666. *juliana Ver dados creci 21. 536. * marcos Ver dados creci 11. 954. *alessandra Ver dados creci 22. 591. *juliano Ver dados creci 10. 929. *daniel Ver dados creci 24. 419. *tatiane Ver dados creci 28. 463. * lucas Ver dados creci 26. 200. *gabriel silva - Ver dados creci 26. 962. *dênis - Ver dados creci 18. 700. * juliana mahon Ver dados creci 28. 712. * samuel - Ver dados creci 28. 275. * gabriel brandão - Ver dados creci 28. 403. avaliamos seu imóvel. • Avaliação gratuita para Venda e Locação; • Atendimento personalizado, todos os dias da semana e agilidade na venda; • Venha e tenha uma experiência extraordinária; • LeideVer dados Instagram: @leidecorretora_ / Ver dados@gmail. com. *Alguns dados do anúncio poderão sofrer alteração sem aviso prévio.",
               "Link":None,
               "_PREV_Link":"https://www.wimoveis.com.br/propriedades/qi-12-carpe-diem-2-quartos-1-suite-mobiliado-e-2993128603.html"
            },
            {
               "_STATUS":"ADDED",
               "Position":"17",
               "Valor":"R$ 139.999",
               "Condominio":"R$ 200 Condominio",
               "Titulo":"Rua Rua 5 Chácara 115",
               "Local":"Vicente Pires, Vicente Pires",
               "Area":"42 m² tot.",
               "Quartos":"1 quartos",
               "Banheiro":"1 banheiro",
               "Garagens":None,
               "Descricao":"Residencial. Rua 06 da Vicente Pires-df. Excelente 1 Quarto com fogão cooktop, 42m² Cozinha americana. Prédio sem Elevador. Primeiro andar. Comércio amplo ao redor. Portaria sem porteiro. Oportunidade Biaxou de R$ 160mil por R$ 140mil. Não aceita financiamento. Cessão de direitos. Agende sua visita Ver dados. Meu Imóvel Imobiliária Creci Jurídico Ver dados. Trabalhamos com compra, venda, revenda, administração (aluguel) e avaliação! Adquira agora sua carta de consórcio. ( Somos operadores Rodobens, Santander, Itaú, Adecon, Âncora) Cartas de imóveis, automóveis, motos, serviços com condições incríveis e contemplação rápida!! Aprovamos financiamento bancário sem custos (Caixa, Itau, Santander, Bradesco, brb, Inter) - 16/05/2024",
               "Link":"https://www.wimoveis.com.br/propriedades/rua-6-vicente-pires-residencial-1-quarto-42m-sem-vaga-2956737845.html"
            },
            {
               "_STATUS":"REMOVED",
               "Position":None,
               "_PREV_Position":"18",
               "Valor":None,
               "_PREV_Valor":"R$ 570.000",
               "Condominio":None,
               "_PREV_Condominio":"R$ 698 Condominio",
               "Titulo":None,
               "_PREV_Titulo":"Rua 7 Residencial Jardim Brasil",
               "Local":None,
               "_PREV_Local":"Aguas Norte, Águas Claras",
               "Area":None,
               "_PREV_Area":"63 m² tot.",
               "Quartos":None,
               "_PREV_Quartos":"3 quartos",
               "Banheiro":None,
               "_PREV_Banheiro":"2 ban.",
               "Garagens":None,
               "_PREV_Garagens":"1 vaga",
               "Descricao":None,
               "_PREV_Descricao":"Unq vende com exclusividade. Se você procura um apartamento que une conforto, praticidade e uma localização privilegiada, esta é a sua chance! Este encantador apartamento de 3 quartos, sendo 1 suíte, oferece um espaço acolhedor e funcional para você e sua família. Características do Imóvel: 3 Quartos (1 Suíte): Espaços bem distribuídos e aconchegantes para acomodar toda a família. Armários Planejados: Quartos e cozinha equipados com armários planejados, garantindo organização e praticidade. Varanda: Um espaço perfeito para desfrutar de momentos relaxantes e contemplar a vista. 63m²: Ambientes amplos e bem distribuídos para maior conforto. Condomínio com Lazer Completo! Excelente Localização: Próximo a escolas, padarias, mercados e comércio em geral, oferecendo facilidade e conveniência no dia a dia. Área de Lazer Completa: Piscina, academia, salão de festas, churrasqueira e muito mais, proporcionando diversão e relaxamento para toda a família. Localização Privilegiada: Este apartamento está situado em uma localização estratégica, próximo a uma variedade de serviços e comércios, facilitando o acesso a tudo que você precisa no seu cotidiano. Não perca esta oportunidade de garantir um espaço confortável e cheio de comodidades para você e sua família! Para mais informações e agendamento de visitas, entre em contato conosco. Este pode ser o apartamento dos seus sonhos! Agende sua visita! (61) 9. Ver dados (WhatsApp / Telegram) As informações financeiras e de metragem privativa poderão ser atualizadas a qualquer momento conforme a Certidão de Matrícula do Imóvel.",
               "Link":None,
               "_PREV_Link":"https://www.wimoveis.com.br/propriedades/apartamento-2-andar-com-altura-de-5-andar-2989274578.html"
            },
            {
               "_STATUS":"ADDED",
               "Position":"18",
               "Valor":"R$ 3.472.972",
               "Condominio":None,
               "Titulo":"SQSW 500 BLOCO H PARQUE ESPLANADA SUDOESTE - BRASÍLIA",
               "Local":"Sudoeste, Brasília",
               "Area":"186 m² tot.",
               "Quartos":"4 quartos",
               "Banheiro":"6 ban.",
               "Garagens":"3 vaga",
               "Descricao":"Mas um grande lançamento na Quadra 500 do Sudoeste, 4 suítes. Unidades de 151 m² - 146 m² - 156 m². Entre em contato comigo. unidade — H — 301 — 186, 20 m², canto, vazado, vista livre para o verde. 3 vagas soltas, sendo 1 destinada para possível instalação de tomada para carro elétrico. 1 Bicicletário. 1 bicicletário no subsolo de garagem. Sala com várias possibilidades, layout e varanda. Sala íntima. Os quartos com as suas respectivas suítes e janela de correr. Suíte – master com ampla claridade, espaço para mesa de cabeceira, cama, king size e vários armários ou closet. Banheiro com 2 cubas amplas e 2 chuveiros. Cozinha com janela, espaço para armários e dce completo com saída de serviço. Aquecedor individual a gás externo instalado. Projeto estrutural com lajes planas que melhoram o isolamento acústico e dão grandes flexibilidades de layout. O seu lazer. Piscina aquecida, solarium, sauna, duchas e banheiro. Academia. Espaço gourmet totalmente equipado. Salão de festas, brinquedoteca. A quadra. A quadra já está pronta, o que temos são as construções dos condomínios. Próxima ao parque ecológico das Sucupiras. Parquinho infantil com piso emborrachado. 158 câmeras de segurança espalhados pela quadra. Urbanização em bloquete. Praças e jardins de convivência. Taxa de decoração da área comum: R$ 18. 000, 00. Agende a sua visita. Unidade sujeita a disponibilidade. Os Valores podem ser alterados sem aviso. * * Tenho preço, qualidade, localização, prazo, forma de pagamento. Ou seja, ótima oportunidade para você! Agende a sua visita. (Ver dados* temos pouquíssimas unidades neste padrão. Todos os anúncios pertencem A mesma imobiliária mudando apenas O corretor. * Tenho preço, qualidade, localização, prazo, forma de pagamento. Ou seja, ótima oportunidade para você! Tags. : #parksul #2quartosparksul #sudoeste #octogonal #coberturalinearnoParksul #coberturalinearembrasilia #apartamentodequatroquartosembrasilia #apartamentodetresquartosnoparksul #apartamentodedoisquartosembrasilia #coberturaduplexnoparksul #coberturaduplexembrasiliaparksulprimeresidence #ilhasmauricioparksul #ilhasmauricioresidence #livingparksul #apartamentosproximoaoaeroportodebrasilia #superquadraparksul #superquadralivingparksul #vistaparksul #parkstudios #apartamentodeumquartonoparksul #apartamentonosudoeste #lancamentodequatroquartosnoparksul #apartamentonovosembrasilia #apartamentosproximoaosetorhospitalaembrasilia #apartamentosproximosaoparkshoppingembrasilia #apartamentosproximosacolegioembrasilia #apartamentosproximoaolagoembrasilia #apartamentopertodesupermercadosembrasilia #apartamentoscomlazercompletoembrasilia #apartamentocomlazercompletonoparksul #apartamentoscomsegurancaembrasilia #casanlagosul #casanolagosulempontadepicoleseco #sudoesteembrasilia #asasul #asanorte #cruzeirovelho #cruzeironovo #condominiofechadonoparksul #eleganceparksul #excellenceparksul #vistaparksul #veniceparksul #parkstudiosembrasilia #livingparksul #eleganceparksul #lancamentosnoparksulembrasilia #excellenceparksul #parksulprimeresidence #vistaparksul #sudoestebrasilia #lagosul #lagonorte #imoveisembrasilia #casapark #parkshoppingbrasilia #veniceparksul #parkdacidadebrasilia #advancehotelembrasilia#conforto#exclusividade#lazer#comodidade#sudoeste#asasul#asanorte#apartamentonaplanta#sudoeste500apartamentona planta#",
               "Link":"https://www.wimoveis.com.br/propriedades/sudoeste-4-quartos-com-suites-vazado-canto-nascente-3-2994839962.html"
            },
            {
               "_STATUS":"REMOVED",
               "Position":None,
               "_PREV_Position":"19",
               "Valor":None,
               "_PREV_Valor":"R$ 2.590.000",
               "Condominio":None,
               "_PREV_Condominio":None,
               "Titulo":None,
               "_PREV_Titulo":"sqsw",
               "Local":None,
               "_PREV_Local":"Sudoeste, Brasília",
               "Area":None,
               "_PREV_Area":"188 m² tot.",
               "Quartos":None,
               "_PREV_Quartos":"3 quartos",
               "Banheiro":None,
               "_PREV_Banheiro":"5 ban.",
               "Garagens":None,
               "_PREV_Garagens":"2 vaga",
               "Descricao":None,
               "_PREV_Descricao":"Apartamento no Edifício Maison Toulouse, Sudoeste. Localização: sqsw 101. Área Privativa: 188m² Descrição: Descubra a elegância e o conforto neste magnífico apartamento, localizado no Sudoeste. Com detalhes exclusivos, este imóvel oferece: Sala de estar ampla e acolhedora. Andar alto com vista livre. Varanda aberta espaçosa para desfrutar de momentos relaxantes. Sala de jantar generosa para refeições memoráveis. 3 suítes e 1 quarto com varanda, proporcionando privacidade e conforto. Lavabo para conveniência dos moradores e convidados. Dependência completa de empregada com armários. Cozinha e área de serviço repletas de armários de alta qualidade. 2 vagas de garagem para comodidade dos residentes. Características Adicionais: Acabamentos nobres: parte seca em madeira nobre, parte molhada em granito, porcelanato e cerâmica. Posição perpendicular ao sol, proporcionando iluminação natural. Projeto luminotécnico em excelente estado de conservação. Prédio diferenciado, com localização privilegiada em bairro consolidado. Este apartamento é a definição de luxo e requinte no coração do Sudoeste. Aproveite a oportunidade de viver em um ambiente sofisticado e exclusivo, com toda a praticidade e conforto que você merece. Entre em contato para mais informações e agende uma visita para conhecer pessoalmente todas as vantagens desse imóvel extraordinário.",
               "Link":None,
               "_PREV_Link":"https://www.wimoveis.com.br/propriedades/apartamento-sudoeste-quadra-101-2997581802.html"
            },
            {
               "_STATUS":"ADDED",
               "Position":"19",
               "Valor":"R$ 2.099.000",
               "Condominio":None,
               "Titulo":"Condomínio RK",
               "Local":"Região Dos Lagos, Sobradinho",
               "Area":"502 m² tot.",
               "Quartos":"3 quartos",
               "Banheiro":"6 ban.",
               "Garagens":"2 vaga",
               "Descricao":"A gm Imóveis vende casa no condomínio Residencial rk um dos mais valorizados da Região dos Lagos. Condomínio fechado, com toda infraestrutura, portaria 24 horas, câmeras, pista de caminhada, parques infantis e quadras de esportes. Ficando apenas 16 minutos do centro de Brasília e um dos melhores locais para se viver no df. O que acha de adquirir um imóvel localizado em uma das regiões mais valorizadas de Brasília e um dos condomínios mais requisitados? * distribuição do imóvel* * Lote com 504 m² * Área construída com 400 m² * Excelente casa nova com projeto inovador. * Com vista livre. * Iluminação em led. * Acabamento de excelente padrão. * Laje em toda a casa. * 04 suítes. * Sala 03 ambientes com o pé direito alto. * Lavabo. * Cozinha com bancada. * Churrasqueira. * Piscina aquecida. * Banheiro externo. * Lavanderia. * Garagem para 03 carros. Condomínio rk conta com serviços adicionais: Aulas de pilates, capoeira kids, escolinha de futebol, jiu-jitsu, judô, karatê, ginástica treinamento funcional, escolinha de vôlei, yoga entre outras. * Venha conhecer e surpreenda-se! Marque agora sua visita. * observações importantes * * A área do imóvel é uma estimativa e deverá ser confirmada junto à documentação do imóvel. * O valor referente à taxa de condomínio poderá sofrer alteração sem prévio aviso, a qual deverá ser confirmada pelo interessado na compra, junto à administração do condomínio. * Somos especialistas há mais de 15 anos no mercado imobiliário. Prestamos consultoria completa para vendedores e compradores. * Fazemos avaliação de crédito e aprovamos seu financiamento bancário na Caixa Econômica Federal, sendo o imóvel passível de financiamento. * unidade grande colorado. * creci Jurídico: Ver dados. * Ligue agora (61) Ver dados /(61) Ver dados (Whatsapp) * Marque uma visita com nossos consultores. * Atendimentos de segunda-feira a sexta-feira das 08h às 18h. * Sábado das 08h às 17h.",
               "Link":"https://www.wimoveis.com.br/propriedades/casa-condominio-04-suites-pisicina-churrasqueira-2986912429.html"
            },
            {
               "_STATUS":"REMOVED",
               "Position":None,
               "_PREV_Position":"20",
               "Valor":None,
               "_PREV_Valor":"R$ 2.053.887",
               "Condominio":None,
               "_PREV_Condominio":"R$ 2.053.887",
               "Titulo":None,
               "_PREV_Titulo":"SQN 402 BL. M",
               "Local":None,
               "_PREV_Local":"Asa Norte, Brasília",
               "Area":None,
               "_PREV_Area":"6 plan.",
               "Quartos":None,
               "_PREV_Quartos":"1 a 2 quartos",
               "Banheiro":None,
               "_PREV_Banheiro":"111 m² tot.",
               "Garagens":None,
               "_PREV_Garagens":None,
               "Descricao":None,
               "_PREV_Descricao":"Cobertura à venda na Asa Norte - Em obras! Apartamento Asa Norte - kasa, 1 e 2 quartos. Coberturas de 1 e 2 quartos com 111, 68m² até 127, 88 m² com vaga de garagem. Asa Norte, um bairro jovem e já consolidado, onde a modernidade se funde com tradição. Aqui, a infraestrutura completa se mescla com uma paisagem natural e deslumbrante. Sinta-se imerso na natureza enquanto desfruta do que há de mais contemporâneo na vida urbana. Kasa, o novo Lotus é diferente. Personalidade com cores e linhas próprias, feito para você. Formas orgânicas e arquitetura com pureza de elementos criam uma atmosfera inconfundível, tudo cercado por um bosque com ipês, paus-brasil e jacarandás. Na fachada concreto aparente e muita luz natural. Além da localização estratégica, que deixa tudo mais perto. O novo é moderno, ser singular é a nova estética. • Preço referente unidade A- 302 com 111, 68 M².",
               "Link":None,
               "_PREV_Link":"https://www.wimoveis.com.br/propriedades/cobertura-asa-norte-kasa-2995691088.html"
            },
            {
               "_STATUS":"ADDED",
               "Position":"20",
               "Valor":"Consultar preço",
               "Condominio":"Consultar preço",
               "Titulo":"Rua Quaresmeira 2ª, Lote 13",
               "Local":"Guara I, Guará",
               "Area":"1 plan.",
               "Quartos":"3 quartos",
               "Banheiro":None,
               "Garagens":None,
               "Descricao":"Seja bem-vindo(a) às coberturas privativas e lineares de 3 suítes, do Ilha Bela Residence, localizado no Guará I: Experimente o Excepcional. Mais um empreendimento com a marca da solidez, segurança e qualidade construtiva Emplavi, há 41 anos construindo histórias felizes em Brasília, com mais 31. 000 imóveis entregues no prazo. A simetria perfeita entre beleza arquitetônica e funcionalidade, no lugar ideal para os melhores momentos em família ou na companhia dos amigos, com lazer completo e diferenciado, áreas comuns diversificadas e funcionais e espaços amplos revestidos de requinte e sofisticação, que proporcionam conforto e praticidade, o Ilha Bela residence apresenta uma proposta única de viver e morar em Brasília, com a qualidade de vida que você e sua família sempre sonharam, harmonizando a intensidade da uma grande cidade, com momentos únicos de convivência, relaxamento e muita diversão. O Ilha Bela Residence está localizado no Guará I, em frente à eptg, a poucos minutos do Plano Piloto e com acesso rápido a toda uma gama de equipamentos públicos, parques, shoppings, supermercados, feiras, escolas, farmácias e comércio em geral e às principais vias de acesso ao centro de Brasília, além de duas estações de metrô e dois terminais de ônibus. Com metragens que variam entre 205, 58m² e 216, 08m² e com 03 vagas de garagem, as coberturas lineares do Ilha Bela residence, oferecem uma experiência inigualável de exclusividade, conforto e sofisticação, mesclando elementos nobres e contemporâneos, com modernidade, funcionalidade e uma vista privilegiada, que juntos, promovem uma atmosfera de bem-estar e pura inspiração. Um novo estilo de viver o excepcional espera por e você e sua família. Fale com um corretor credenciado Emplavi, agende uma visita no ponto de vendas e conheça as obras aceleradas. As imagens apresentadas são meramente ilustrativas. Unidades sujeitas à disponibilidade.",
               "Link":"https://www.wimoveis.com.br/propriedades/cobertura-ilha-bela-residence-03-suites-guara-i-2986019805.html"
            }
         ]
      }
   },
   "event":"task.finishedSuccessfully"
}





def extracao_imoveis(body):
    # Extrai do body do webhook os dados relevante para tabela wimoveis
    wimoveis_data = body['task']['capturedLists']['extracao wimoveis']
    if wimoveis_data:
        df = pd.DataFrame(wimoveis_data)
        print(df.columns)
        return df



if __name__ == '__main__':
    extracao_imoveis(body)
